// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
// ds4-svelte — OX Design System DS-4
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

// ── Tokens DS-4 ──────────────────────────────
export {
  OX,
  makePluginTheme,
  generateOXRootCSS,
  generateOXShadowCSS,
  THEME_TINAX,
  THEME_ZAPAX,
  THEME_LC,
  THEME_DEFAULT,
  // backward-compat aliases
  DS3,
  generateDS3RootCSS,
  generateDS3ShadowCSS,
} from './design-system/tokens'
export type { OXType, OXType as OXTokenType, DS3Type, PluginTheme } from './design-system/tokens'
export type { OxShellNavItem, OxShellSidebarItem, OxShellSidebarDivider, OxShellSidebarSectionLabel, OxShellToolbarItem } from './components/shell/shell-types.js'

// ── Variant types ─────────────────────────────
export type ButtonVariant = 'filled' | 'tonal' | 'outlined' | 'text' | 'elevated' | 'error-filled' | 'error-tonal' | 'error-outlined' | 'danger'
export type CardVariant = 'elevated' | 'filled' | 'outlined'
export type ChipVariant = 'assist' | 'filter' | 'input'
export type ToastVariant = 'default' | 'error'

// ── UI Components ─────────────────────────────
export {
  OxFloatingPanel,
  OxSwitch,
  OxButton,
  OxAccordion,
  OxTabs,
  OxAvatar,
  OxRating,
  OxProgress,
  OxSlider,
  OxSegment,
  OxPagination,
  OxCombobox,
  OxCarousel,
  OxCard,
  OxChip,
  OxBadge,
  OxDialog,
  OxNavigation,
  OxToast,
  OxMenu,
  OxPopover,
  OxPortal,
  OxTooltip,
  OxToggleGroup,
  OxTagsInput,
  OxAppBar,
  OxBranding,
  OxGlobalSearch,
  OxAppShell,
  OxNavMenuItem,
  OxSteps,
  OxCircularProgress,
  OxFileUpload,
  OxDivider,
  OxEditable,
  OxHoverCard,
  OxImageCropper,
  OxField,
  OxNumberInput,
  OxPasswordInput,
  OxPinInput,
  OxNavigationDrawer,
  OxNavigationMenu,
  OxAvatarMenu,
  OxRailContextProvider,
  OxRailItem,
  OxRailMenu,
  OxRailLabel,
  OxRailActionBtn,
  OxToolbarSectionLabel,
  OxCardCrmContact,
  OxCardCrmCalendar,
  OxCardCrmMap,
  OxCrmCalendar,
  OxCrmCalendarItem,
  OxCrmCalendarBadge,
  OxCrmSidebarItem,
  OxSnackbar,
  OxAuroraText,
  OxBacklight,
  OxLetterpress,
  OxTextShadow,
  OxDisplacementReveal,
  OxTextReveal,
  OxHeroAnimated,
  OxVideoText,
  OxHueShift,
  OxList,
  OxListItem,
  OxListContactSmall,
  OxListLogLarge,
  OxTable,
  OxEntityTable,
  entityActionsHtml,
  entityActionsDropdownHtml,
  OxTableGrouped,
  OxSplitter,
  OxTerminalLog,
  OxTimer,
  OxClock,
  OxToaster,
  OxToasterSimple,
  OxToasterTimer,
  OxToastItem,
  OxConfetti,
  OxSplash,
  OxTriStateSwitch,
  OxMockLaptop,
  OxMockPhone,
  OxMockTablet,
  OxMockImac,
  OxGradientText,
  OxWave,
  OxWaveOcean,
  OxWaveOceanDouble,
} from './components'

// ── Toast store helper ───────────────────────
export { createStore as createOxToaster } from '@zag-js/toast'
